Scrum 55 make structure in frontend prettier and create component files
FHallengreen/sparehub pull request #14
Opened 2024-12-05 13:26 UTC by DanielStarckLorenzen

This pull request includes significant refactoring and improvements to the frontend codebase. The changes mainly involve reorganizing file structures, improving error handling, and adding new API functions for dispatch and order management.

### File structure reorganization:
* [`frontend/src/App.tsx`](diffhunk://#diff-e56cb91573ddb6a97ecd071925fe26504bb5a65f921dc64c63e534162950e1ebL4-R13): Updated import paths to reflect the new file structure, moving components to their respective feature directories.

### Error handling improvements:
* [`frontend/src/api/api.ts`](diffhunk://#diff-9099dfcb65b652e332f3cf44e249de1a3272067a71f96d8c059b4a7ba77b01ebL19-R19): Enhanced error handling in request and response interceptors to provide more descriptive error messages. [[1]](diffhunk://#diff-9099dfcb65b652e332f3cf44e249de1a3272067a71f96d8c059b4a7ba77b01ebL19-R19) [[2]](diffhunk://#diff-9099dfcb65b652e332f3cf44e249de1a3272067a71f96d8c059b4a7ba77b01ebL34-R34)

### New API functions:
* [`frontend/src/api/authApi.ts`](diffhunk://#diff-68a4688a7789670356f242a733450ab4860de6f401572780deb2aee5af12cc30R1-R12): Added `login` and `logout` functions to handle authentication.
* [`frontend/src/api/dispatchApi.ts`](diffhunk://#diff-1722928c50b7f57bdf5a2d8660b857acf6e575494b79fb40daea8c5ae5dd7a83R1-R29): Added functions for CRUD operations on dispatches, including `getDispatches`, `getDispatch`, `createDispatch`, `updateDispatch`, and `deleteDispatch`.
* [`frontend/src/api/orderApi.ts`](diffhunk://#diff-0bc02812221fc9f3bc679d2bd3bc616efa35859afb27d5a694961a440d1df33eR1-R19): Added functions to fetch orders and order details by ID.

### Component removals:
* `frontend/src/components/DispatchDetailPage.tsx` and `frontend/src/components/DispatchPage.tsx`: Removed these components as their functionality has been moved to the new API functions and refactored components. [[1]](diffhunk://#diff-19033e1a1d84e78beb6487dfa4a4ad8a2ebf9a03e00fe59aacc53aa1e820edaaL1-L232) [[2]](diffhunk://#diff-fb9d7412d3fe9e86323f1e2bc974f4d60d5bf1ba66bc46849b83e3dc599ff7a7L1-L194)

2024-12-05 13:52 UTC, FHallengreen requested changes

2024-12-05 13:52 UTC, FHallengreen commented on frontend/src/api/authApi.ts
> +  const response = await api.post('/auth/login', { email, password });
Skal være /api/auth/login

2024-12-10 09:31 UTC, albe194e approved these changes
👍

2024-12-10 09:37 UTC, FHallengreen approved these changes

2024-12-10 09:37 UTC, merged