Port, Vessel, Vessel At Port and Owner Crud
FHallengreen/sparehub pull request #8
Opened 2024-11-28 21:26 UTC by adrnl1ne

CRUD for Port, Vessel, Vessel At Port and Owner Crud

2024-11-29 09:04 UTC, FHallengreen requested changes

2024-11-29 09:04 UTC, FHallengreen commented on backend/SpareHub/Domain/Models/VesselAtPort.cs
> +    public required string PortId { get; set; }
Skal skiftes tilbage til init da den er immutable

2024-11-29 09:04 UTC, FHallengreen commented on backend/SpareHub/Persistence/MySql/PortEntity.cs
> +    public required int Id { get; set; }
Skal også have init

2024-11-29 09:04 UTC, FHallengreen commented on backend/SpareHub/Persistence/MySql/VesselEntity.cs
> +    // Consider making Owner nullable if you want to allow creation without it
Fjern lige ChatGPT comments :P

2024-11-29 09:04 UTC, FHallengreen commented on backend/SpareHub/Service/MySql/Vessel/VesselMySqlService.cs
> +    /*public async Task<List<VesselResponse>> GetVesselsBySearchQuery(string? searchQuery = "")
Skal implementeres igen

2024-12-03 15:17 UTC, FHallengreen approved these changes
Ok

2024-12-03 15:24 UTC, adrnl1ne commented
Merge conflicts solved

2024-12-03 15:30 UTC, adrnl1ne commented
Required attribute not added

2024-12-03 15:30 UTC, merged